# ==================== Test Environment ====================
spring.sql.init.mode=never

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}
# JWT
# jwt.secret=${JWT_SECRET:}

app.demo-mode=false

security.login-lock.enabled=true
security.login-lock.max-fails=5
security.login-lock.lock-minutes=5

logging.level.root=INFO
logging.level.com.pancosky.cartradeadmin=INFO
logging.file.name=logs/admin-backend-test.log
