// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: http://shengtaiprd.pancosky.com/5dadmin/
// Generated: 2026-06-14T02:58:26.229Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#03060a' | '#515b6d' | '#252b39' | '#ffffff' | '#140bec' | '#e4e7eb' | '#d7000d' | '#c12a00' | '#5d73ff' | '#00a849' | '#005122' | '#f2f4f7' | '#1f1dff' | '#0e07ae' | '#91a4ff' | '#a8a8b0' | '#090d16' | '#475b7c' | '#fee0e2' | '#d5fae9' | '#343dff' | '#dae2ff' | '#008134' | '#f5060a' | '#de7000' | '#ffc5c9' | '#08063c' | '#beccff' | '#fff6d3' | '#fc5200' | '#ec0853' | '#ff0418';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '700' | '500' | '900' | '800';

export type SpacingToken = '2px' | '16px' | '20px' | '24px' | '40px';

export type RadiusToken = '4px' | '8px' | '12px' | '16px';

export type DurationToken = '150ms' | '200ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
