/** 车源管理 mock 数据与筛选项 */
import type { Vehicle } from './types'

/** 筛选用省份列表，与 SEED_VEHICLES 中 province 字段对应 */
export const provinces = ['安徽省', '浙江省', '天津市', '江苏省', '广东省']

/** 车源管理页初始 mock 数据，覆盖多种渠道、状态与能源类型 */
export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'CAR-1002',
    brand: '特斯拉 (Tesla)',
    model: 'Model 3 2023 焕新版',
    energyType: '纯电',
    registerDate: '2023年08月',
    mileage: '2.8w 公里',
    region: '浙江省-杭州市',
    province: '浙江省',
    channel: 'Dealer',
    seller: { name: '李建波', nickname: '波子哥', type: '5D 合作车辆' },
    price: '20.50',
    guidePrice: '25.99',
    status: 'reserved',
    detail: {
      description: '法拍竞价代拍车源，已完成5D核心128项整备认证。双电机性能好车。',
      mileageKm: '2.80万公里',
      emissionStandard: '-',
      displacement: '纯电',
      colors: '默认色|默认色',
      transmission: '自动',
      manufacturer: '特斯拉中国',
      vehicleType: 'Model Y',
      newCarPrice: '26.0万',
      usageNature: '非营运',
      insuranceExpiry: '2027-01-30',
      sellerId: 'USR-8821',
      sellerPhone: '13988776655',
      sellerRole: '个人车主',
      specs: [
        { label: '车源所在地区', value: '浙江省-杭州市', highlight: true },
        { label: '厂商/车系', value: '特斯拉 Model Y' },
        { label: '动力类型', value: '纯电动 299马力' },
        { label: '三围尺寸', value: '4750*1921*1624mm' },
        { label: '上市时间', value: '2024年02月' },
        { label: '厂商', value: '特斯拉中国' },
        { label: '能源类型', value: '纯电动' },
        { label: '环保标准', value: '-' },
        { label: '最大功率(kW)', value: '220' },
        { label: '最大扭矩(N·m)', value: '440' },
        { label: '车门数', value: '5' },
        { label: '座位数', value: '5' },
        { label: '左舵/右舵', value: '左舵' },
        { label: '油箱容积(L)', value: '-' },
        { label: '整车质量(kg)', value: '1909' },
        { label: '排量(mL)', value: '-' },
        { label: '进气形式', value: '-' },
        { label: '气缸排列形式', value: '-' },
        { label: '气缸数', value: '-' },
        { label: '燃油标号', value: '-' },
      ],
    },
  },
  {
    id: 'CAR-1003',
    brand: '保时捷 (Porsche)',
    model: '911 Carrera 3.0T',
    registerDate: '2021年11月',
    mileage: '3.5w 公里',
    region: '天津市-天津市',
    province: '天津市',
    channel: 'Auction',
    seller: { name: '苏宏达', nickname: '宏达总', type: '5D 合作车辆' },
    price: '91.00',
    guidePrice: '129.80',
    status: 'listed',
    detail: {
      description: '司法拍卖标的车辆，手续齐全，原厂保养记录完整，精品车况。',
      mileageKm: '3.50万公里',
      emissionStandard: '国VI',
      displacement: '3.0T',
      colors: '白色|黑色',
      transmission: 'PDK双离合',
      manufacturer: '保时捷',
      vehicleType: '跑车',
      newCarPrice: '129.8万',
      usageNature: '非营运',
      insuranceExpiry: '2026-11-15',
      sellerId: 'USR-7732',
      sellerPhone: '13811223344',
      sellerRole: '5D 合作车辆',
      specs: [
        { label: '车源所在地区', value: '天津市-天津市', highlight: true },
        { label: '厂商/车系', value: '保时捷 911' },
        { label: '动力类型', value: '汽油 385马力' },
        { label: '三围尺寸', value: '4519*1852*1298mm' },
        { label: '上市时间', value: '2021年09月' },
        { label: '厂商', value: '保时捷' },
        { label: '能源类型', value: '汽油' },
        { label: '环保标准', value: '国VI' },
        { label: '最大功率(kW)', value: '283' },
        { label: '最大扭矩(N·m)', value: '450' },
        { label: '车门数', value: '2' },
        { label: '座位数', value: '4' },
        { label: '左舵/右舵', value: '左舵' },
        { label: '油箱容积(L)', value: '64' },
        { label: '整车质量(kg)', value: '1510' },
        { label: '排量(mL)', value: '2981' },
        { label: '进气形式', value: '涡轮增压' },
        { label: '气缸排列形式', value: 'H型' },
        { label: '气缸数', value: '6' },
        { label: '燃油标号', value: '95号' },
      ],
    },
  },
  {
    id: 'CAR-1004',
    brand: '奥迪 (Audi)',
    model: 'A6L 45 TFSI 臻选型',
    registerDate: '2022年10月',
    mileage: '5.8w 公里',
    region: '江苏省-南京市',
    province: '江苏省',
    channel: 'DirectUser',
    seller: { name: '刘本山', nickname: '山叔', type: '个人车商' },
    price: '28.20',
    guidePrice: '45.49',
    status: 'pending_review',
    detail: {
      description: '个人车商寄售，全程4S店保养，无重大事故，内饰成色新。',
      mileageKm: '5.80万公里',
      emissionStandard: '国VI',
      displacement: '2.0T',
      colors: '黑色|棕色',
      transmission: '7速双离合',
      manufacturer: '一汽-大众奥迪',
      vehicleType: '中大型车',
      newCarPrice: '45.49万',
      usageNature: '非营运',
      insuranceExpiry: '2026-08-20',
      sellerId: 'USR-6610',
      sellerPhone: '13755667788',
      sellerRole: '个人车商',
      specs: [
        { label: '车源所在地区', value: '江苏省-南京市', highlight: true },
        { label: '厂商/车系', value: '奥迪 A6L' },
        { label: '动力类型', value: '汽油 252马力' },
        { label: '三围尺寸', value: '5038*1886*1475mm' },
        { label: '上市时间', value: '2022年06月' },
        { label: '厂商', value: '一汽-大众奥迪' },
        { label: '能源类型', value: '汽油' },
        { label: '环保标准', value: '国VI' },
        { label: '最大功率(kW)', value: '185' },
        { label: '最大扭矩(N·m)', value: '370' },
        { label: '车门数', value: '4' },
        { label: '座位数', value: '5' },
        { label: '左舵/右舵', value: '左舵' },
        { label: '油箱容积(L)', value: '73' },
        { label: '整车质量(kg)', value: '1750' },
        { label: '排量(mL)', value: '1984' },
        { label: '进气形式', value: '涡轮增压' },
        { label: '气缸排列形式', value: 'L型' },
        { label: '气缸数', value: '4' },
        { label: '燃油标号', value: '95号' },
      ],
    },
  },
  {
    id: 'CAR-1005',
    brand: '极氪 (Zeekr)',
    model: '极氪001 ME版 100kWh',
    energyType: '纯电',
    registerDate: '2023年06月',
    mileage: '1.9w 公里',
    region: '江苏省-苏州市',
    province: '江苏省',
    channel: 'Dealer',
    seller: { name: '陈伟东', nickname: '阿东', type: '5D 合作车辆' },
    price: '23.80',
    guidePrice: '34.90',
    status: 'sold',
    detail: {
      description: '极氪官方认证二手车，电池健康度98%，一手车源，已完成平台交割。',
      mileageKm: '1.90万公里',
      emissionStandard: '-',
      displacement: '纯电',
      colors: '灰色|灰蓝',
      transmission: '自动',
      manufacturer: '极氪',
      vehicleType: '猎装车',
      newCarPrice: '34.90万',
      usageNature: '非营运',
      insuranceExpiry: '2026-05-10',
      sellerId: 'USR-5544',
      sellerPhone: '13699887766',
      sellerRole: '5D 合作车辆',
      specs: [
        { label: '车源所在地区', value: '江苏省-苏州市', highlight: true },
        { label: '厂商/车系', value: '极氪 001' },
        { label: '动力类型', value: '纯电动 544马力' },
        { label: '三围尺寸', value: '4970*1999*1560mm' },
        { label: '上市时间', value: '2023年04月' },
        { label: '厂商', value: '极氪' },
        { label: '能源类型', value: '纯电动' },
        { label: '环保标准', value: '-' },
        { label: '最大功率(kW)', value: '400' },
        { label: '最大扭矩(N·m)', value: '686' },
        { label: '车门数', value: '5' },
        { label: '座位数', value: '5' },
        { label: '左舵/右舵', value: '左舵' },
        { label: '油箱容积(L)', value: '-' },
        { label: '整车质量(kg)', value: '2350' },
        { label: '排量(mL)', value: '-' },
        { label: '进气形式', value: '-' },
        { label: '气缸排列形式', value: '-' },
        { label: '气缸数', value: '-' },
        { label: '燃油标号', value: '-' },
      ],
    },
  },
  {
    id: 'CAR-1006',
    brand: '丰田 (Toyota)',
    model: '凯美瑞 2.5G 豪华版',
    energyType: '混动',
    registerDate: '2020年07月',
    mileage: '8.2w 公里',
    region: '广东省-广州市',
    province: '广东省',
    channel: 'TradeIn',
    seller: { name: '刘强', nickname: '大强', type: '个人车商' },
    price: '11.50',
    guidePrice: '21.98',
    status: 'listed',
    detail: {
      description: '置换车源，家用代步首选，保养及时，轮胎刚换，性价比突出。',
      mileageKm: '8.20万公里',
      emissionStandard: '国VI',
      displacement: '2.5L混动',
      colors: '银色|米色',
      transmission: 'E-CVT',
      manufacturer: '广汽丰田',
      vehicleType: '中型车',
      newCarPrice: '21.98万',
      usageNature: '非营运',
      insuranceExpiry: '2026-06-30',
      sellerId: 'USR-4401',
      sellerPhone: '13566778899',
      sellerRole: '个人车商',
      specs: [
        { label: '车源所在地区', value: '广东省-广州市', highlight: true },
        { label: '厂商/车系', value: '丰田 凯美瑞' },
        { label: '动力类型', value: '油电混合 178马力' },
        { label: '三围尺寸', value: '4885*1840*1455mm' },
        { label: '上市时间', value: '2020年05月' },
        { label: '厂商', value: '广汽丰田' },
        { label: '能源类型', value: '油电混合' },
        { label: '环保标准', value: '国VI' },
        { label: '最大功率(kW)', value: '131' },
        { label: '最大扭矩(N·m)', value: '221' },
        { label: '车门数', value: '4' },
        { label: '座位数', value: '5' },
        { label: '左舵/右舵', value: '左舵' },
        { label: '油箱容积(L)', value: '50' },
        { label: '整车质量(kg)', value: '1590' },
        { label: '排量(mL)', value: '2487' },
        { label: '进气形式', value: '自然吸气' },
        { label: '气缸排列形式', value: 'L型' },
        { label: '气缸数', value: '4' },
        { label: '燃油标号', value: '92号' },
      ],
    },
  },
]
