export const getAuctionList = (params) => uni.http.get('/auctions', { params })
export const getAuctionDetail = (id) => uni.http.get(`/auctions/${id}`)
export const createAuction = (data) => uni.http.post('/auctions', data)
export const cancelAuction = (id) => uni.http.post(`/auctions/${id}/cancel`)
export const watchAuction = (id) => uni.http.post(`/auctions/${id}/watch`)
export const unwatchAuction = (id) => uni.http.delete(`/auctions/${id}/watch`)
export const placeBid = (data) => uni.http.post('/auctions/bids', data)
export const getBidRecords = (id, params) => uni.http.get(`/auctions/${id}/bids`, { params })
export const getCurrentPrice = (id) => uni.http.get(`/auctions/${id}/current-price`)
