export const getCarList = (params) => uni.http.get('/cars', { params })
export const getCarDetail = (id) => uni.http.get(`/cars/${id}`)
export const createCar = (data) => uni.http.post('/cars', data)
export const updateCar = (id, data) => uni.http.put(`/cars/${id}`, data)
export const deleteCar = (id) => uni.http.delete(`/cars/${id}`)
export const favoriteCar = (id) => uni.http.post(`/cars/${id}/favorite`)
export const unfavoriteCar = (id) => uni.http.delete(`/cars/${id}/favorite`)
export const getFavorites = (params) => uni.http.get('/cars/favorites', { params })
export const getRecommend = () => uni.http.get('/cars/recommend')
export const contactSeller = (id) => uni.http.post(`/cars/${id}/contact`)
export const downloadImage = (carId, imageId) => uni.http.get(`/cars/${carId}/images/${imageId}/download`)
export const getMyCarSource = (params) => uni.http.get('/cars/mine', { params })
