export const getConversations = () => uni.http.get('/chat/conversations')
export const createConversation = (data) => uni.http.post('/chat/conversations', data)
export const getChatMessages = (id, params) => uni.http.get(`/chat/conversations/${id}/messages`, { params })
export const sendChatMessage = (id, data) => uni.http.post(`/chat/conversations/${id}/messages`, data)
export const markConversationRead = (id) => uni.http.post(`/chat/conversations/${id}/read`)
