export const getDeposit = () => uni.$u.http.get('/finance/deposit')
export const rechargeDeposit = (data) => uni.$u.http.post('/finance/deposit/recharge', data)
export const withdrawDeposit = (data) => uni.$u.http.post('/finance/deposit/withdraw', data)
export const getDepositRecords = (params) => uni.$u.http.get('/finance/deposit/records', { params })
export const getCredit = () => uni.$u.http.get('/finance/credit')
export const applyCredit = (data) => uni.$u.http.post('/finance/credit/apply', data)
