export const followUser = (userId) => uni.http.post(`/follows/${userId}`)
export const unfollowUser = (userId) => uni.http.delete(`/follows/${userId}`)
export const getFollowList = (params) => uni.http.get('/follows', { params })
export const getMyFollows = (params) => uni.http.get('/follows', { params })
export const checkFollowed = (userId) => uni.http.get(`/follows/${userId}/check`)
