export const getMessageList = (params) => uni.http.get('/messages', { params })
export const getUnreadCount = () => uni.http.get('/messages/unread-count')
export const markRead = (id) => uni.http.put(`/messages/${id}/read`)
export const markAllRead = () => uni.http.put('/messages/read-all')
export const deleteMessage = (id) => uni.http.delete(`/messages/${id}`)
export const getNotificationSettings = () => uni.http.get('/messages/notification-settings')
export const updateNotificationSettings = (data) => uni.http.put('/messages/notification-settings', data)
