export const getOrderList = (params) => uni.http.get('/orders', { params })
export const getOrderStats = () => uni.http.get('/orders/stats')
export const getOrderDetail = (id) => uni.http.get(`/orders/${id}`)
export const createOrder = (data) => uni.http.post('/orders', data)
export const confirmOrder = (id) => uni.http.put(`/orders/${id}/confirm`)
export const cancelOrder = (id, reason) => uni.http.put(`/orders/${id}/cancel`, { reason })
export const payDeposit = (id) => uni.http.put(`/orders/${id}/pay-deposit`)
export const completeOrder = (id) => uni.http.put(`/orders/${id}/complete`)
export const createDispute = (id, data) => uni.http.post(`/orders/${id}/dispute`, data)
export const submitContract = (id, data) => uni.http.post(`/orders/${id}/contract`, data)
export const updateContract = (id, data) => uni.http.put(`/orders/${id}/contract`, data)
export const confirmContract = (id) => uni.http.put(`/orders/${id}/contract/confirm`)
export const getContract = (id) => uni.http.get(`/orders/${id}/contract`)
export const terminateOrder = (id, data) => uni.http.post(`/orders/${id}/terminate`, data)
export const getTerminateCount = (id) => uni.http.get(`/orders/${id}/terminate/count`)
export const getOrderLogs = (id) => uni.http.get(`/orders/${id}/logs`)
